alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8xaqnqv1igwrucoj72r539ntq
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists Phone cascade
drop table if exists Student cascade
